name: CI
on: pull_request

jobs:
  integration:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup
        run: ./setup.sh

      - name: Check aws
        run: aws --version
      - name: Check homebrew
        run: brew --version
      - name: Check gh
        run: gh --version

      - name: Check deploying
        run: git s
